server {
    listen 80;              # Escucha en el puerto 80 (HTTP)
    server_name localhost;  # Nombre del servidor
    root /usr/share/nginx/html;  # Carpeta donde están los archivos del build
    index index.html;       # Archivo principal que carga

    location / {
        try_files $uri $uri/ /index.html;  # ← LA MÁS IMPORTANTE
    }
}